# Site settings
title: Portfolio Wouter
email: wouter@wouter.nl
description: > # this means to ignore newlines until "baseurl:"
  Dit is mijn geweldige nieuwe portfolio website. Have fun!
baseurl: "/jekyll-test-site" # the subpath of your site, e.g. /blog/
<<<<<<< HEAD
url: "http://wrldwidewouter.gihub.io" # the base hostname & protocol for your site
=======
url: "http://wrldwidewouter.github.io" # the base hostname & protocol for your site
>>>>>>> 39459bb50e5b12adba94483b72c9144ba800ac8b
twitter_username: wouter
github_username:  wrldwidewouter

# Build settings
markdown: kramdown
# highlighter: rouge
highlighter: pygments
