# Site settings
title: Portfolio Wouter
email: w.j.vosl@st.hanze.nl
description: > # this means to ignore newlines until "baseurl:"
  Dit is mijn geweldige nieuwe portfolio website. Have fun!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wouter
github_username:  wouter

# Build settings
markdown: kramdown
highlighter: rouge
